name: Release Please

on:
  push:
    branches:
      - main
      - 1.x

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          target-branch: ${{ github.ref_name }}

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created == 'true' }}

      - name: Use pnpm
        uses: pnpm/action-setup@v2
        if: ${{ steps.release.outputs.release_created == 'true' }}

      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        if: ${{ steps.release.outputs.release_created == 'true' }}
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install Dependencies
        if: ${{ steps.release.outputs.release_created == 'true' }}
        run: pnpm --filter=!@jsonapi-serde/docs install

      - name: Build
        if: ${{ steps.release.outputs.release_created == 'true' }}
        run: pnpm --filter=!@jsonapi-serde/docs -r build

      - name: Publish
        if: ${{ steps.release.outputs.release_created == 'true' }}
        run: pnpm --filter=!@jsonapi-serde/docs --filter=!@jsonapi-serde/core -r publish --access public
