name: Release Please

on:
  push:
    branches:
      - main
      - 1.x

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    outputs:
      any_release_created: ${{ steps.check_release.outputs.any_release_created }}

    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}
          target-branch: ${{ github.ref_name }}

      - name: Check if any package released
        id: check_release
        uses: actions/github-script@v7
        env:
          PATHS_RELEASED: ${{ toJSON(steps.release.outputs.paths_released) }}
        with:
          script: |
            const pathsReleased = JSON.parse(process.env.PATHS_RELEASED);
            core.setOutput('any_release_created', pathsReleased.length > 0 ? 'true' : 'false');

  publish:
    runs-on: ubuntu-latest
    needs: release-please
    if: needs.release-please.outputs.any_release_created == 'true'

    steps:
      - uses: actions/checkout@v4

      - name: Use pnpm
        uses: pnpm/action-setup@v2

      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm --filter=!@jsonapi-serde/docs install

      - name: Build
        run: pnpm --filter=!@jsonapi-serde/docs -r build

      - name: Publish
        run: pnpm --filter=!@jsonapi-serde/docs -r publish --access public
